#!/usr/bin/env sh
set -eu
python3 tests/test_save_schema.py
python3 tests/test_save_codec.py
python3 tests/test_save_journal.py
python3 tests/test_save_backend_contract.py
python3 tests/test_save_fs_backend_contract.py
python3 tests/test_gesture.py
python3 tests/test_gesture_trace.py
python3 tests/test_handoff.py
python3 tests/test_sync_packet.py
python3 tests/test_sync_receive.py
python3 tests/test_sync_wire.py
python3 tests/test_sync_retry_stress.py
python3 tests/test_folder_transport_sim.py
python3 tests/test_roundtrip_replay.py
python3 tests/test_trace_buffer.py
python3 tests/test_trace_wire.py
python3 tests/test_tempo.py
python3 tests/test_object_biography.py
python3 tests/test_echo.py
python3 tests/test_fault_injection.py
python3 tests/test_sealed_game_sim.py
python3 tests/test_runtime_checkpoint.py
python3 tests/test_runtime_persistence.py
python3 tests/test_relation_persistence.py
python3 tests/test_relation_export.py
python3 tests/test_semantic_runtime.py
python3 tools/ivv_check.py
python3 tools/blind_pass1.py
python3 tools/blind_pass2.py
python3 tools/blind_pass3.py

python3 tests/test_multimodal_schema.py
