#pragma once
typedef enum {
  ACT_NONE = 0,
  ACT_MOVE_UP,
  ACT_MOVE_DOWN,
  ACT_MOVE_LEFT,
  ACT_MOVE_RIGHT,
  ACT_PRIMARY,
  ACT_SECONDARY,
  ACT_MENU,
  ACT_PUM,
  ACT_POINTER_MOVE,
  ACT_POINTER_PRESS,
  ACT_CONTEXT_L1,
  ACT_CONTEXT_R1,
  ACT_CONTEXT_L2,
  ACT_CONTEXT_R2
} SemanticAction;
